### ISSUE TITLE
wrong pathes to fly

### ISSUE THREAD

**Issue by Kas-O-dam** [SantiagoCdeveloper/Game#1]
Good game, edit pathes from graphic/fly/**f**ly(n).png to graphic/fly/**F**ly(n).png
![github_issue](https://github.com/SantiagoCdeveloper/Game/assets/100534559/f65c21ec-2a3b-4311-8690-4d6846352e17)

**Comment by SantiagoCdeveloper** [comment]
Hey donskoy. Thanks for see my game i really appreciate this, thanks for your advice i'll do it soon

**Comment by SantiagoCdeveloper** [comment]
Hey dinskoy. Thanks for see my game i really appreciate this, thanks for your advice i'll do it soon
